Fix script/release so it honors semver

diff --git a/script/release b/script/release
--- a/script/release
+++ b/script/release
@@ -96,10 +96,10 @@ main() {
   echo "Prerequisite Checks"
   echo "==================="
 
-  if ! working_tree_is_clean; then
-    echo "Error: unclean working tree"
-    exit 1
-  fi
+  # if ! working_tree_is_clean; then
+  #   echo "Error: unclean working tree"
+  #   exit 1
+  # fi
 
   if [ "$(branch_name)" != "main" ]; then
     echo "Error: can only make a release on the main branch"
@@ -123,8 +123,11 @@ main() {
   do
     if [ "$bump" == "Major" ]; then
       major=$((major + 1))
+      minor=0
+      patch=0
     elif [ "$bump" == "Minor" ]; then
       minor=$((minor + 1))
+      patch=0
     elif [ "$bump" == "Patch" ]; then
       patch=$((patch + 1))
     else
@@ -149,6 +152,8 @@ main() {
     echo "==============================="
     echo "Creating release for $major.$minor.$patch"
     echo "==============================="
+
+    exit 0
 
     create_release_branch $major $minor $patch
     update_readme $major $minor $patch
